if [ "${INCGEGL}" == "Y" ]; then
# SOFT INCFFMPEG="Y"
  INCJSONGLIB="Y"
  INCLENSFUN="Y"
  INCLIBRAW="Y"
  INCLIBRSVG="Y"
  INCLIBWEBP="Y"
  INCLUAJIT="Y"
  INCOPENEXR="Y"
  INCSDL="Y"
  INCSUITESPARSE="Y"
fi
