if [ "${INCQTFIVE}" == "Y" ]; then
  INCLIBXKBCOMMON="Y"
  INCGSTREAMER="Y"
  INCHUNSPELL="Y"
  INCHYPHEN="Y"
  INCOPENALSOFT="Y"
  INCWOFFTWO="Y"
  INCXCBUTILIMAGE="Y"
  INCXCBUTILKEYSYMS="Y"
  INCXCBUTILRENDERUTIL="Y"
  INCXCBUTILWM="Y"
fi
