#!/bin/sh
# Initial script for Linux Live Kit
# Author: Tomas M <http://www.linux-live.org/>
# Author: Brett Kuskie <fullaxx@gmail.com>

export PATH=".:/:/usr/sbin:/usr/bin:/sbin:/bin"

# Install busybox symlinks
/sbin/busybox --install -s /sbin

# busybox installs a link to itself from init
# we remove it so as not to interefere with the cleanup script
/sbin/rm /sbin/init

# load any library functions we find in /lib
for ILIBFILE in /lib/*.irfs.lib; do
#  echo "Sourcing ${ILIBFILE} ..."
  source ${ILIBFILE}
done

transfer_initramfs

MEMORY=/memory
CHANGES=$MEMORY/changes
UNION=$MEMORY/union
DATAMNT=$MEMORY/data
BUNDLES=$MEMORY/bundles

header "Live Kit init <http://www.linux-live.org/>"

init_proc_sysfs

debug_start
                                                                                                                                                       debug_shell
init_devs
init_aufs
# init_zram ZRAM IS A MODULE AT THE MOMENT (and not located in the initramfs)

# find data dir with filesystem bundles
DATA="$(find_data 15 "$DATAMNT")"
                                                                                                                                                      debug_shell
# setup persistent changes, if possible
persistent_changes "$DATA" "$CHANGES"
                                                                                                                                                      debug_shell
# copy to RAM if needed
DATA="$(copy_to_ram "$DATA" "$CHANGES")"
                                                                                                                                                      debug_shell
# init aufs union
init_union "$CHANGES" "$UNION"
                                                                                                                                                      debug_shell
# add data to union
# union_append_bundles "$DATA" "$BUNDLES" "$UNION" MODIFIED FOR RAPIDLINUX
union_append_bundles "$DATA" "$BUNDLES" "$UNION" "base"
union_append_bundles "$DATA" "$BUNDLES" "$UNION" "modules"
                                                                                                                                                      debug_shell
# rootcopy
copy_rootcopy_content "$DATA" "$UNION"

# create empty fstab
fstab_create "$UNION"
                                                                                                                                                      debug_shell
header "Live Kit done, starting RapidLinux"
change_root "$UNION"

header "!!ERROR occured, you shouldn't be here.!!"
/bin/sh
