# 002-utils options
if [ "${INCMOD002UTILS}" == "Y" ]; then
# a family of packages
  INCTCSH="Y"

# Custom Additions
  INCACPI="Y"
  INCATOP="Y"
  INCBINDTOOLS="Y"
  INCCALC="Y"
  INCCOLORTAIL="Y"
  INCCORKSCREW="Y"
  INCCURLFTPFS="Y"
  INCCURLLOADER="Y"
  INCEXFAT="Y"
  INCEXTUNDELETE="Y"
  INCIOPING="Y"
  INCIOTOP="Y"
  INCIPERFTWO="Y"
  INCIPERFTHREE="Y"
  INCIPMITOOL="Y"
  INCLOOPAESSETUP="Y"
  INCMOSH="Y"
  INCNBD="Y"
  INCPROTOBUF="Y"
  INCPROTOBUFC="Y"
  INCXNBD="Y"
fi
