# 002-utils options
if [ "${INCMOD002UTILS}" == "Y" ]; then
# a family of packages
  INCTCSH="Y"

# ap family of packages
  INCCUPS="Y"
  INCDMIDECODE="Y"
  INCTMUX="Y"

# Custom Additions
  INCACPI="Y"
  INCATOP="Y"
  INCBINDTOOLS="Y"
  INCCALC="Y"
  INCCOLORTAIL="Y"
  INCCORKSCREW="Y"
  INCCURLFTPFS="Y"
  INCCURLLOADER="Y"
  INCDAVFSTWO="Y"
  INCEXFAT="Y"
  INCEXTUNDELETE="Y"
  INCHEXYL="Y"
  INCHPINGTHREE="Y"
  INCIOPING="Y"
  INCIOTOP="Y"
  INCIPERFTWO="Y"
  INCIPERFTHREE="Y"
  INCIPMITOOL="Y"
  INCLOOPAESSETUP="Y"
  INCMOSH="Y"
  INCNBD="Y"
  INCPROTOBUF="Y"
  INCPROTOBUFC="Y"
  INCTWEAK="Y"
  INCUDFTOOLS="Y"
  INCXNBD="Y"
fi
