# 005-server options
if [ "${INCMOD005SERVER}" == "Y" ]; then
  INCAPACHEHTTPD="N"
  INCBIND="N"
  INCDNSMASQ="N"
  INCLXC="N"
  INCMARIADB="N"
  INCNETSNMP="N"
  INCPHP="N"
  INCPROFTPD="N"
  INCSAMBA="N"
  INCVSFTPD="N"
fi
