# 005-server options
if [ "${INCMOD005SERVER}" == "Y" ]; then
  INCLXC="N"
  INCMARIADB="N"
  INCPHP="N"
  INCSAMBA="Y"
  INCNETSNMP="N"
  INCAPACHEHTTPD="N"
  INCPROFTPD="N"
  INCVSFTPD="N"

# Custom Additions
  INCLIBMICROHTTPD="Y"
  INCLIBVIRT="Y"
  INCNODEZEROTEN="N"
  INCNODEZEROTWELVE="N"
  INCNODEFOUR="N"
  INCNODESIX="N"
  INCNODEEIGHT="N"
  INCNOVNC="Y"
  INCREDIS="Y"
  INCZEROMQ="Y"
fi
