# 005-server options
if [ "${INCMOD005SERVER}" == "Y" ]; then
# Departure from Default
  INCSAMBA="N"

# Custom Additions
  INCDARKHTTPD="Y"
  INCLIBMICROHTTPD="Y"
  INCLIBVIRT="Y"
  INCLIBWEBSOCKETS="Y"
  INCMONGOCDRIVER="Y"
  INCNGINX="Y"
  INCNNG="Y"
  INCNODEZEROTEN="N"
  INCNODEZEROTWELVE="N"
  INCNODEFOUR="N"
  INCNODESIX="N"
  INCNODEEIGHT="N"
  INCNOVNC="Y"
  INCREDIS="Y"
  INCZEROMQ="Y"
fi
