# 005-server options
if [ "${INCMOD005SERVER}" == "Y" ]; then
# Custom Additions
  INCLIBMICROHTTPD="Y"
  INCLIBVIRT="Y"
  INCLIBWEBSOCKETS="Y"
  INCMONGOCDRIVER="N"
  INCNGINX="N"
  INCNNG="Y"
  INCNODEZEROTEN="N"
  INCNODEZEROTWELVE="N"
  INCNODEFOUR="N"
  INCNODESIX="N"
  INCNODEEIGHT="N"
  INCNOVNC="N"
  INCQUARK="Y"
  INCREDIS="Y"
  INCZEROMQ="Y"
fi
