if [ "${INCGNURADIO}" == "Y" ]; then
  INCBOOST="Y"
  INCCHEETAHTHREE="Y"
  INCGSL="Y"
  INCLXML="Y"
  INCMAKO="Y"
  INCNUMPY="Y"
  INCORC="Y"
  INCPYGTK="Y"
  INCPYQT="Y"
  INCPYTHONSIX="Y"
  INCPYZMQ="Y"
  INCQWT="Y"
  INCSWIG="Y"
fi

# WHAT NEEDS CPPUNIT?
# INCCPPUNIT="Y"

# gnu-radio companion needs:
# INCCHEETAH="Y"
# INCLXML="Y"
# INCNUMPY="Y"
# INCPYGTK="Y"
