if [ "${INCTERMINATOR}" == "Y" ]; then
  INCGSETTINGSDESLTOPSCHEMAS="Y"
  INCGOBJECTINTROSPECTION="Y"
  INCGTKTHREE="Y"
  INCPYCAIRO="Y"
  INCPYGOBJECT="Y"
  INCPYGTK="Y"
  INCPYTHON="Y"
  INCPYTHONCONFIGOBJ="Y"
  INCPYTHONPSUTIL="Y"
  INCPYTHONSIX="Y"
  INCVTE="Y"
fi
