if [ "${INCTERMINATOR}" == "Y" ]; then
  INCCONFIGOBJ="Y"
  INCGSETTINGSDESLTOPSCHEMAS="Y"
  INCGOBJECTINTROSPECTION="Y"
  INCGTKTHREE="Y"
  INCPSUTIL="Y"
  INCPYCAIRO="Y"
  INCPYGOBJECT="Y"
  INCPYGTK="Y"
  INCPYTHON="Y"
  INCPYTHONSIX="Y"
  INCVTE="Y"
fi
