if [ "${INCJUPYTER}" == "Y" ]; then
  INCBLEACH="Y"
  INCJEDI="Y"
  INCJINJATWO="Y"
  INCJSONSCHEMA="Y"
  INCPICKLESHARE="Y"
  INCPROMPTTOOLKIT="Y"
  INCPYTHONREQUESTS="Y"
  INCPYTHONSIX="Y"
  INCPYZMQ="Y"
  INCTORNADO="Y"
  INCTRAITLETS="Y"
fi
