if [ "${INCGNURADIO}" == "Y" ]; then
  INCBOOST="Y"
  INCCLICK="Y"
  INCGSL="Y"
  INCMAKO="Y"
  INCNUMPY="Y"
  INCORC="Y"
  INCPYGTK="Y"
  INCPYTHONSIX="Y"
  INCPYYAML="Y"
  INCQTFIVE="Y"
  INCSWIG="Y"
  INCZEROMQ="Y"
fi
