if [ "${INCSAMBA}" == "Y" ]; then
  INCGPGME="Y"
  INCJANSSON="Y"
  INCLIBAIO="Y"
  INCLIBARCHIVE="Y"
  INCLIBASSUAN="Y"
  INCLIBUNWIND="Y"
  INCLIBURING="Y"
  INCLMDB="Y"
  INCTALLOC="Y"
  INCTEVENT="Y"
fi
