if [ "${INCVLC}" == "Y" ]; then
  INCAFIFTYTWO="Y"
  INCALSA="Y"
  INCFFMPEG="Y"
  INCFLAC="Y"
  INCLIBDVBPSI="Y"
  INCLIBDVDNAV="Y"
  INCLIBDVDREAD="Y"
  INCLIBMAD="Y"
  INCLIBMPEGTWO="Y"
  INCLIBOGG="Y"
  INCLIBPNG="Y"
  INCLIBRSVG="Y"
  INCLIBTHEORA="Y"
  INCLIBVA="Y"
  INCLIBVDPAU="Y"
  INCLIBVORBIS="Y"
  INCMPGONETWOTHREE="Y"
  INCOPUS="Y"
  INCPULSE="Y"
  INCSDL="Y"
fi

# INCSVGALIB="Y"
# INCX264="Y"
# INCX265="Y"
# SOFT SAMBA

# libstream_out_chromecast_plugin.so needs /usr/lib64/libprotobuf-lite.so
