if [ "${INCMOZILLAFIREFOX}" == "Y" ]; then
  INCADWAITAICONTHEME="Y"
  INCALSA="Y"
  INCDBUSGLIB="Y"
  INCEXPAT="Y"
  INCFRIBIDI="Y"
  INCGTKTWO="Y"
  INCGTKTHREE="Y"
  INCHICOLORICONTHEME="Y"
  INCMESA="Y"
  INCMOZILLANSS="Y"
  INCSTARTUPNOTIFICATION="Y"
  INCLIBXCOMPOSITE="Y"
fi
