if [ "${INCVLC}" == "Y" ]; then
  INCALSA="Y"
  INCFFMPEG="Y"
  INCFLAC="Y"
  INCLIBDVBPSI="Y"
  INCLIBMPEGTWO="Y"
  INCLIBOGG="Y"
  INCLIBPNG="Y"
  INCLIBRSVG="Y"
  INCLIBTHEORA="Y"
  INCLIBVA="Y"
  INCLIBVDPAU="Y"
  INCLIBVORBIS="Y"
  INCMPGONETWOTHREE="Y"
  INCOPUS="Y"
  INCPULSE="Y"
  INCSDL="Y"
fi

# INCSVGALIB="Y"
# INCX264="Y"
# INCX265="Y"
# SOFT SAMBA
