# 002-utils options
if [ "${INCMOD002UTILS}" == "Y" ]; then
  INCKERNELFIRMWARE="N"

  INCALSA="N"
  INCPULSE="N"
  INCESOUND="N"

  INCGNUPG="N"
  INCGNUPG2="Y"
  INCLOGROTATE="N"
  INCLMSENSORS="Y"
  INCMCABBER="Y"
  INCMIDNIGHTCOMMANDER="Y"
  INCMPG123="N"
  INCMTR="N"
  INCSERF="N"
  INCSYSSTAT="Y"
  INCXNBD="Y"
fi
