# 006-devel options
if [ "${INCMOD006DEVEL}" == "Y" ]; then
# ap family of packages
  INCBC="Y"
  INCLINUXDOCTOOLS="Y"
  INCRPM="Y"
  INCTEXINFO="Y"
  INCVIM="Y"

# d family of packages
  INCAUTOCONF="Y"
  INCAUTOMAKE="Y"
  INCBINUTILS="Y"
  INCBISON="Y"
  INCCMAKE="Y"
  INCCVS="N"
  INCDOXYGEN="N"
# expat found in 009-xmodlibs
  INCEXPAT="Y"
  INCFLEX="Y"
  INCGCC="Y"
  INCGCCGO="N"
  INCGCCGPLUSPLUS="Y"
  INCGDB="Y"
  INCGETTEXT="Y"
  INCGETTEXTTOOLS="Y"
  INCGIT="Y"
  INCGPERF="N"
  INCGUILE="Y"
  INCINTLTOOL="Y"
  INCLIBTOOL="Y"
  INCLLVM="Y"
  INCMFOUR="Y"
  INCMAKE="Y"
  INCMERCURIAL="N"
  INCNASM="Y"
  INCNINJA="N"
  INCOPENCLHEADERS="N"
  INCPARALLEL="Y"
  INCPATCHELF="Y"
  INCPKGCONFIG="Y"
  INCPMAKE="N"
  INCSTRACE="Y"
  INCSUBVERSION="N"
  INCYASM="Y"

# e family of packages
  INCEMACS="N"
fi
