# 010-xorg options
if [ "${INCMOD010XORG}" == "Y" ]; then
  INCXDESKTOPENVIRONMENT="N"
  INCADOBEFONTS="N"
  INCBITSTREAMFONTS="N"
  INCMESA="N"

# Video Card Selection
  INCXF86VIDEOAMDGPU="N"
  INCXF86VIDEOAST="N"
  INCXF86VIDEOATI="N"
  INCXF86VIDEOINTEL="N"
  INCXF86VIDEOMGA="N"
  INCXF86VIDEONOUVEAU="N"
  INCXF86VIDEOVMWARE="N"

# Simple X Apps
  INCMAKEDEPEND="N"
  INCMOTIF="N"
  INCTRANSSET="N"
  INCXBACKLIGHT="N"
  INCXCALC="N"
  INCXDG="N"
  INCXDPYINFO="N"
  INCXDRIINFO="N"
  INCXKILL="N"
  INCXMAN="Y"
  INCXMESSAGE="Y"
  INCXMORE="Y"
  INCXPROP="N"
  INCXSET="Y"
  INCXKBMAP="N"
  INCXSETROOT="N"
  INCXVINFO="N"
  INCXWD="N"
  INCXWININFO="N"
fi
