# 012-xapps options
if [ "${INCMOD012XAPPS}" == "Y" ]; then
# Desktop ENV
  INCFLUXBOX="Y"
  INCXFCE="N"
  INCXFCETUMBLER="N"
  INCXFCEPOWERMANAGER="N"
  INCXFCESETTINGS="N"

# Apps
  INCAUDACIOUS="N"
  INCGIMP="N"
  INCGKRELLM="N"
  INCGPARTED="N"
  INCHEXCHAT="N"
  INCMOZILLAFIREFOX="N"
  INCMOZILLATHUNDERBIRD="N"
  INCMPLAYER="N"
  INCRDESKTOP="N"
  INCRXVTUNICODE="N"
  INCXLOCK="N"
  INCXMMS="N"
  INCXPAINT="N"
  INCTIGERVNC="N"
fi
