# 002-utils options
if [ "${INCMOD002UTILS}" == "Y" ]; then
# Custom Additions
  INCACPI="Y"
  INCBINDTOOLS="Y"
  INCCALC="Y"
  INCCOLORTAIL="Y"
  INCCORKSCREW="Y"
  INCCURLFTPFS="Y"
  INCCURLLOADER="Y"
  INCEXTUNDELETE="Y"
  INCIPERFTWO="Y"
  INCIPERFTHREE="Y"
  INCLOOPAESSETUP="Y"
  INCMOSH="Y"
  INCNUMACTL="Y"
  INCPROTOBUF="Y"
  INCPROTOBUFC="Y"
fi
