# 002-utils options
if [ "${INCMOD002UTILS}" == "Y" ]; then
# a family of packages
  INCINFOZIP="Y"
  INCMLOCATE="Y"

# ap family of packages
  INCPOWERTOP="Y"
  INCTMUX="Y"

# n family of packages
  INCNETCAT="Y"
  INCSOCAT="Y"
  INCSSHFS="Y"
  INCTELNET="Y"

# Custom Additions (Previously Shrapnel)
  INCAG="Y"
  INCARPSCAN="Y"
  INCAXEL="Y"
  INCBMON="Y"
  INCBROOT="Y"
  INCBTOPPLUSPLUS="Y"
  INCCALC="Y"
  INCCCAT="Y"
  INCCOLORTAIL="Y"
  INCCTOP="Y"
  INCCURLLOADER="Y"
  INCDARKHTTPD="Y"
  INCDELTA="Y"
  INCDRY="Y"
  INCGPING="Y"
  INCIPERFTWO="Y"
  INCIPERFTHREE="Y"
  INCIPMITOOL="Y"
  INCLAZYGIT="Y"
  INCLOOPAESSETUP="Y"
  INCMICRO="Y"
  INCNBD="Y"
  INCNBDKIT="Y"
  INCNCDU="Y"
  INCNNN="Y"
  INCNUMACTL="Y"
  INCPV="Y"
  INCWOL="Y"
fi
