MODNUM="030"
MODNAME="multilib"
MODULE="${MODNUM}-${MODNAME}.xzm"
BUILDBASE="/tmp/${PROJNAME}"
DIR="${BUILDBASE}/${MODNUM}/fs"
NEWDIR="${BUILDBASE}/${MODNUM}/fs32"

SLACKPKGDIR="${PACKAGESDIR}/slackware/Slack32-${SLACKPKGVERS}/slackware"
SLACKEXTRA="${PACKAGESDIR}/slackware/Slack32-${SLACKPKGVERS}/extra"
