# 005-server options
if [ "${INCMOD005SERVER}" == "Y" ]; then
# Departure from Default
  INCDNSMASQ="Y"
  INCPROFTPD="Y"
  INCSAMBA="Y"
  INCVSFTPD="Y"

# Custom Additions
  INCDARKHTTPD="Y"
  INCLIBMICROHTTPD="Y"
  INCLIBVIRT="Y"
  INCNGINX="Y"
  INCNNG="Y"
  INCNODEZEROTEN="N"
  INCNODEZEROTWELVE="N"
  INCNODEFOUR="N"
  INCNODESIX="N"
  INCNODEEIGHT="Y"
  INCNOVNC="Y"
  INCREDIS="Y"
  INCZEROMQ="Y"
fi
