# 012-xapps options
if [ "${INCMOD012XAPPS}" == "Y" ]; then
# Desktop ENV
  INCFLUXBOX="Y"
  INCOPENBOX="Y"

# Set a default DE, if you desire
  DEFAULTDE="openbox"

# Apps
  INCAUDACIOUS="Y"
  INCGFTP="Y"
  INCGIMP="Y"
  INCGKRELLM="Y"
  INCGNUPLOT="Y"
  INCGPARTED="Y"
  INCMOZILLAFIREFOX="Y"
  INCMOZILLATHUNDERBIRD="N"
  INCSEAMONKEY="N"
  INCMPLAYER="N"
  INCPAVUCONTROL="Y"
  INCRDESKTOP="Y"
  INCRXVTUNICODE="Y"
  INCSOMA="N"
  INCVIMGVIM="Y"
  INCXINE="N"
  INCXLOCK="Y"
  INCXPAINT="Y"

# extra family of packages
  INCRECORDMYDESKTOP="Y"
  INCTIGERVNC="Y"

# Custom Additions
  INCBLUEFISH="N"
  INCBLUEFISHTWO="Y"
  INCETERM="Y"
  INCEVINCE="Y"
  INCFBPANEL="Y"
  INCGEANY="Y"
  INCHSETROOT="Y"
  INCOBCONF="Y"
  INCVLC="Y"
  INCXFE="Y"

# Tagged for inclusion into Modules dir by baseoutput
  INCCHROME="Y"
  INCVSCODE="Y"
fi
