# 003-interp options
if [ "${INCMOD003INTERP}" == "Y" ]; then

# n family of packages
  INCPSSH="N"

# Custom Additions
# INCBOKEH="N"
  INCFTPSYNC="N"
  INCGNURADIO="Y"
  INCJUPYTER="N"
  INCKEEPNOTE="Y"
# INCSCIPY pulls INCNUMPY
  INCPASTEBINIT="N"
# INCNOVNC pulls INCWEBSOCKIFY
# INCOPENBOX pulls INCPYXDG
  INCVIRTUALENV="Y"
fi
