# 006-devel options
if [ "${INCMOD006DEVEL}" == "Y" ]; then
# Departure from Default
  INCCVS="Y"
  INCDOXYGEN="Y"
  INCEMACS="Y"
  INCMERCURIAL="Y"
  INCOPENCLHEADERS="Y"
  INCSUBVERSION="N"

# Custom Additions
  INCANJUTA="N"
  INCASTYLE="Y"
  INCCGDB="Y"
  INCCODEEXAMPLES="Y"
  INCMEDIT="Y"
  INCVALGRIND="Y"
  INCVALKYRIE="N"
fi
