# 012-xapps options
if [ "${INCMOD012XAPPS}" == "Y" ]; then
# Desktop ENV
  INCBLACKBOX="N"
  INCFLUXBOX="Y"
  INCOPENBOX="Y"
  INCXFCE="N"
  INCXFCETUMBLER="N"
  INCXFCEPOWERMANAGER="N"
  INCXFCESETTINGS="N"

# Set a default DE, if you desire
  DEFAULTDE="openbox"

# Apps
  INCAUDACIOUS="Y"
  INCGFTP="N"
  INCGIMP="Y"
  INCGKRELLM="Y"
  INCGPARTED="Y"
  INCHEXCHAT="N"
  INCMOZILLAFIREFOX="Y"
  INCMOZILLATHUNDERBIRD="N"
  INCMPLAYER="Y"
  INCRDESKTOP="Y"
  INCRXVTUNICODE="N"
  INCTIGERVNC="Y"
  INCXINE="Y"
  INCXLOCK="N"
  INCXMMS="N"
  INCXPAINT="Y"
  INCXPDF="N"

# Custom Additions
  INCBLUEFISH="N"
  INCBLUEFISHTWO="Y"
  INCETERM="Y"
  INCFBPANEL="Y"
  INCGEANY="Y"
  INCHSETROOT="Y"
  INCOBCONF="Y"
  INCXFE="Y"
fi
