# 012-xapps options
if [ "${INCMOD012XAPPS}" == "Y" ]; then
# Desktop ENV
  INCFLUXBOX="Y"
  INCOPENBOX="Y"

# Set a default DE, if you desire
  DEFAULTDE="openbox"

# Apps
  INCAUDACIOUS="Y"
  INCGIMP="Y"
  INCGKRELLM="Y"
  INCGPARTED="Y"
  INCMOZILLAFIREFOX="Y"
  INCMOZILLATHUNDERBIRD="Y"
  INCMPLAYER="Y"
  INCRDESKTOP="Y"
  INCRXVTUNICODE="Y"
  INCSOMA="Y"
  INCXINE="Y"
  INCXPAINT="Y"

# extra family of packages
  INCTIGERVNC="Y"

# Custom Additions
  INCBLUEFISH="N"
  INCBLUEFISHTWO="N"
  INCETERM="Y"
  INCEVINCE="Y"
  INCFBPANEL="Y"
  INCGEANY="Y"
  INCHSETROOT="Y"
  INCOBCONF="Y"
  INCXFE="N"
fi
