# 012-xapps options
if [ "${INCMOD012XAPPS}" == "Y" ]; then
# Desktop ENV
  INCFLUXBOX="Y"
  INCOPENBOX="Y"

# Set a default DE, if you desire
  DEFAULTDE="openbox"

# Apps
  INCAUDACIOUS="Y"
  INCGFTP="Y"
  INCGIMP="Y"
  INCGKRELLM="Y"
  INCGNUPLOT="Y"
  INCGPA="N"
  INCGPARTED="Y"
  INCMOZILLAFIREFOX="Y"
  INCMOZILLATHUNDERBIRD="Y"
  INCSEAMONKEY="N"
  INCMPLAYER="Y"
  INCPAVUCONTROL="Y"
  INCPIDGIN="N"
  INCRDESKTOP="Y"
  INCRXVTUNICODE="Y"
  INCSSR="N"
  INCSOMA="Y"
  INCVIMGVIM="Y"
  INCXINE="N"
  INCXLOCK="N"
  INCXPAINT="Y"
  INCXPDF="Y"

# extra family of packages
  INCRECORDMYDESKTOP="Y"
  INCTIGERVNC="Y"

# Custom Additions
  INCANJUTA="N"
  INCBLUEFISH="Y"
  INCBLUEFISHTWO="N"
  INCETERM="Y"
  INCEVINCE="Y"
  INCFBPANEL="Y"
  INCGEANY="Y"
  INCGHEX="Y"
  INCGRAVEMAN="Y"
  INCHSETROOT="Y"
  INCKITTY="Y"
  INCMPV="Y"
  INCOBCONF="Y"
  INCSLOCK="Y"
  INCST="Y"
  INCTILDA="N"
  INCVLC="Y"
  INCWIRESHARK="Y"
  INCXAUTOLOCK="Y"
  INCXFE="Y"

# Tagged for inclusion into Modules dir by baseoutput
  INCCHROME="Y"
  INCLIBREOFFICE="Y"
  INCVSCODE="N"
fi
