# 012-xapps options
if [ "${INCMOD012XAPPS}" == "Y" ]; then
# Desktop ENV
  INCBLACKBOX="N"
  INCFLUXBOX="Y"
  INCXFCE="N"
  INCXFCETUMBLER="N"
  INCXFCEPOWERMANAGER="N"
  INCXFCESETTINGS="N"

# Set a default DE, if you desire
  DEFAULTDE="fluxbox"

# Apps
  INCAUDACIOUS="Y"
  INCGEANY="Y"
  INCGFTP="N"
  INCGIMP="Y"
  INCGKRELLM="Y"
  INCGPARTED="Y"
  INCHEXCHAT="N"
  INCMOZILLAFIREFOX="Y"
  INCMOZILLATHUNDERBIRD="N"
  INCMPLAYER="Y"
  INCRDESKTOP="Y"
  INCRXVTUNICODE="N"
  INCXINE="Y"
  INCXLOCK="N"
  INCXMMS="N"
  INCXPAINT="Y"
  INCXPDF="N"
  INCTIGERVNC="Y"
fi
