# 002-utils options
if [ "${INCMOD002UTILS}" == "Y" ]; then
# Departure from default
  INCIRSSI="Y"
  INCKERNELFIRMWARE="Y"
  INCNMAP="Y"
  INCOPENVPN="Y"
  INCSCIM="Y"

# Custom Additions
  INCACPI="Y"
  INCBINDTOOLS="Y"
  INCCALC="Y"
  INCCOLORTAIL="Y"
  INCCORKSCREW="Y"
  INCCURLFTPFS="Y"
  INCEXTUNDELETE="Y"
  INCLOOPAESSETUP="Y"
  INCNUMACTL="Y"
fi
