# 002-utils options
if [ "${INCMOD002UTILS}" == "Y" ]; then
# Departure from Default
  INCIRSSI="Y"
  INCKERNELFIRMWARE="Y"
  INCNMAP="Y"
  INCOPENVPN="Y"
  INCSCIM="Y"

# Custom Additions
  INCACPI="Y"
  INCATOP="Y"
  INCBINDTOOLS="Y"
  INCCALC="Y"
  INCCOLORTAIL="Y"
  INCCORKSCREW="Y"
  INCCURLFTPFS="Y"
  INCCURLLOADER="Y"
  INCEXTUNDELETE="Y"
  INCIOPING="Y"
  INCIOTOP="Y"
  INCIPERFTWO="Y"
  INCIPERFTHREE="Y"
  INCLOOPAESSETUP="Y"
  INCMOSH="Y"
  INCNBD="Y"
  INCNUMACTL="Y"
  INCPROTOBUF="Y"
  INCPROTOBUFC="Y"
  INCXNBD="Y"
fi
