# 010-xorg options
if [ "${INCMOD010XORG}" == "Y" ]; then
  INCXDESKTOPENVIRONMENT="N"
  INCADOBEFONTS="N"
  INCBITSTREAMFONTS="N"
  INCMESA="N"

# Video Card Selection
  INCXF86VIDEOAMDGPU="N"
  INCXF86VIDEOAST="N"
  INCXF86VIDEOATI="N"
  INCXF86VIDEOINTEL="Y"
  INCXF86VIDEOMGA="N"
  INCXF86VIDEONOUVEAU="N"
  INCXF86VIDEOVMWARE="N"

# What are these used for?
  INCINTELGPUTOOLS="Y"

# Simple X Apps
  INCMAKEDEPEND="N"
  INCMOTIF="N"
  INCTRANSSET="N"
  INCXBACKLIGHT="Y"
  INCXCALC="Y"
  INCXDG="N"
  INCXDPYINFO="Y"
  INCXDRIINFO="Y"
  INCXKILL="N"
  INCXMAN="Y"
  INCXMESSAGE="Y"
  INCXMORE="Y"
  INCXPROP="N"
  INCXSET="Y"
  INCXKBMAP="N"
  INCXSETROOT="N"
  INCXVINFO="N"
  INCXWD="N"
  INCXWININFO="N"
fi
